### ISSUE TITLE
Comments (POM): Change JBoss references to WildFly ?

### ISSUE THREAD

**Issue by Archangel1C** [wildfly/wildfly-archetypes#11]
In the [POM file](https://github.com/wildfly/wildfly-archetypes/blob/18.0.0.Final/wildfly-jakartaee-webapp-archetype/pom.xml) created by wildfly-jakartaee-webapp-archetype, the comments refer to "JBoss EAP" instead WildFly. Same thing for "version.jboss.bom" and a few other things.

Maybe it's intentional, otherwise I could change it to "WildFly" or something.

**Comment by emmartins** [comment]
Thanks for the report, fixed this with https://github.com/wildfly/wildfly-archetypes/commit/d45f65e92588436e1812cf02a2129bdf32b50ab1
