### ISSUE TITLE
Deprecation warning in subsystem archetype for 31.0.0.Beta1

### ISSUE THREAD

**Issue by WolfgangHG** [wildfly/wildfly-archetypes#72]
This warning is reported when compiling a project created from the subsystem archetype with wildfly-controller 23.0.0.Beta4:
`
[WARNING] /C:/PathTo/wildfly-archetypes/wildfly-subsystem-archetype/testing/example-subsystem/src/main/java/com/acme/example/SubsystemAdd.java:[22,9] AbstractBoottimeAddStepHandler(org.jboss.as.controller.AttributeDefinition...) in org.jboss.as.controller.AbstractBoottimeAddStepHandler has been deprecated and marked for removal
`

The deprecation warning was introduced as part of https://issues.redhat.com/browse/WFCORE-6369, https://issues.redhat.com/browse/WFCORE-6407 and https://issues.redhat.com/browse/WFCORE-6419 and thus pull request: https://github.com/wildfly/wildfly-core/pull/5563

A possible resolution might be taken from the change to the JaxrsSubsystemDefinition: https://github.com/wildfly/wildfly/pull/17007/files#diff-cacbc3164607eba7d1b4f86528b34b816e5ffbbfeb47b2a04c0cfa45c8532803

I have no knowledge of the subsystem internals, so I don't know how to resolve this. Might be a major rework....

@bstansberry Can I ping you, as you did the commit that fixed the JaxrsSubsystemDefinition?

**Comment by WolfgangHG** [comment]
@jmesnil I saw that you did a release of the archetypes for WildFly 31. Might I ping you about this issue?

**Comment by darranl** [comment]
@WolfgangHG Are you in Zulip?  Rather than pinging individuals it could be better to start a thread in one of the streams there to discuss the changes needed or start a discussion on the wildfly-dev list as this is about ongoing WildFly development.

**Comment by WolfgangHG** [comment]
Done - I reused the "archetypes" thread: https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/release.20of.20WildFly.20archetypes/near/418162104
